[package]
description = "Parser/encoder for ASN.1 BER/DER data"
license = "MIT/Apache-2.0"
keywords = ["BER","DER","ASN1","parser","nom"]
homepage = "https://github.com/rusticata/der-parser"
repository = "https://github.com/rusticata/der-parser.git"
name = "der-parser"
version = "4.1.1"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
categories = ["parser-implementations"]
readme = "README.md"
edition = "2018"

include = [
  "LICENSE-*",
  "CHANGELOG.md",
  "README.md",
  "UPGRADING.md",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "bench/*.rs",
  "src/*.rs",
  "src/ber/*.rs",
  "src/der/*.rs",
  "tests/*.rs",
  "der-oid-macro/Cargo.toml",
  "der-oid-macro/src/*.rs",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cookie-factory = { version="0.3.0", optional=true }
nom = "5.0"
rusticata-macros = "2.0.2"
num-traits = "0.2"
num-bigint = { version = "0.3", optional = true }

proc-macro-hack = { version = "0.5", optional = true }
der-oid-macro = { version = "0.2", path = "./der-oid-macro", optional = true}

[features]
default = []
bigint = ["num-bigint"]
serialize = ["cookie-factory"]
unstable = []
oid-macro = ["proc-macro-hack", "der-oid-macro"]

[dev-dependencies]
hex-literal = "0.3"
pretty_assertions = "0.6"

[badges]
travis-ci = { repository = "rusticata/der-parser" }
